require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VendingMachinesController do

  # This should return the minimal set of attributes required to create a valid
  # VendingMachine. As you add validations to VendingMachine, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "serial_number" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VendingMachinesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vending_machines as @vending_machines" do
      vending_machine = VendingMachine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vending_machines).should eq([vending_machine])
    end
  end

  describe "GET show" do
    it "assigns the requested vending_machine as @vending_machine" do
      vending_machine = VendingMachine.create! valid_attributes
      get :show, {:id => vending_machine.to_param}, valid_session
      assigns(:vending_machine).should eq(vending_machine)
    end
  end

  describe "GET new" do
    it "assigns a new vending_machine as @vending_machine" do
      get :new, {}, valid_session
      assigns(:vending_machine).should be_a_new(VendingMachine)
    end
  end

  describe "GET edit" do
    it "assigns the requested vending_machine as @vending_machine" do
      vending_machine = VendingMachine.create! valid_attributes
      get :edit, {:id => vending_machine.to_param}, valid_session
      assigns(:vending_machine).should eq(vending_machine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VendingMachine" do
        expect {
          post :create, {:vending_machine => valid_attributes}, valid_session
        }.to change(VendingMachine, :count).by(1)
      end

      it "assigns a newly created vending_machine as @vending_machine" do
        post :create, {:vending_machine => valid_attributes}, valid_session
        assigns(:vending_machine).should be_a(VendingMachine)
        assigns(:vending_machine).should be_persisted
      end

      it "redirects to the created vending_machine" do
        post :create, {:vending_machine => valid_attributes}, valid_session
        response.should redirect_to(VendingMachine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vending_machine as @vending_machine" do
        # Trigger the behavior that occurs when invalid params are submitted
        VendingMachine.any_instance.stub(:save).and_return(false)
        post :create, {:vending_machine => { "serial_number" => "invalid value" }}, valid_session
        assigns(:vending_machine).should be_a_new(VendingMachine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VendingMachine.any_instance.stub(:save).and_return(false)
        post :create, {:vending_machine => { "serial_number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vending_machine" do
        vending_machine = VendingMachine.create! valid_attributes
        # Assuming there are no other vending_machines in the database, this
        # specifies that the VendingMachine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VendingMachine.any_instance.should_receive(:update_attributes).with({ "serial_number" => "MyString" })
        put :update, {:id => vending_machine.to_param, :vending_machine => { "serial_number" => "MyString" }}, valid_session
      end

      it "assigns the requested vending_machine as @vending_machine" do
        vending_machine = VendingMachine.create! valid_attributes
        put :update, {:id => vending_machine.to_param, :vending_machine => valid_attributes}, valid_session
        assigns(:vending_machine).should eq(vending_machine)
      end

      it "redirects to the vending_machine" do
        vending_machine = VendingMachine.create! valid_attributes
        put :update, {:id => vending_machine.to_param, :vending_machine => valid_attributes}, valid_session
        response.should redirect_to(vending_machine)
      end
    end

    describe "with invalid params" do
      it "assigns the vending_machine as @vending_machine" do
        vending_machine = VendingMachine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VendingMachine.any_instance.stub(:save).and_return(false)
        put :update, {:id => vending_machine.to_param, :vending_machine => { "serial_number" => "invalid value" }}, valid_session
        assigns(:vending_machine).should eq(vending_machine)
      end

      it "re-renders the 'edit' template" do
        vending_machine = VendingMachine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VendingMachine.any_instance.stub(:save).and_return(false)
        put :update, {:id => vending_machine.to_param, :vending_machine => { "serial_number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vending_machine" do
      vending_machine = VendingMachine.create! valid_attributes
      expect {
        delete :destroy, {:id => vending_machine.to_param}, valid_session
      }.to change(VendingMachine, :count).by(-1)
    end

    it "redirects to the vending_machines list" do
      vending_machine = VendingMachine.create! valid_attributes
      delete :destroy, {:id => vending_machine.to_param}, valid_session
      response.should redirect_to(vending_machines_url)
    end
  end

end
